### ISSUE TITLE
Keyboard entry of letters difficult on Android phone

### ISSUE THREAD

**Issue by MMAtHome** [kmc059000/octordle#13]
First of all - great game - kudos to you!
In portrait mode on Android the keyboard is quite challenging to use. I often catch adjoining letters or actions.  I think it would be very helpful for the letters on each row to be offset horizontally by half a character. Possibly also helped by a little more vertical space between the rows.

**Comment by kmc059000** [comment]
Can you try the new version and let me know if it is better or worse? Theres now space between the letters and I've found it easier to type on Android myself.

**Comment by MMAtHome** [comment]
Kenneth,

Thanks so much for your email. I have tried the new version, and the
improvements are excellent. So much better letter positioning and spacing.

It's great to see updates to an already very good game.

Thanks again!

Martin Miles
