### ISSUE TITLE
Completed octordle in 3

### ISSUE THREAD

**Issue by markhagon** [kmc059000/octordle#14]
I entered my first two words and couldn’t scroll up/down so hit the refresh. All eight places showed the same outcome. This seemed impossible and checked with wife - not what she’d had.
Entered EIGHT as third attempt and completed the game with all the tiles swirling.
![C4D7A4D0-0A18-4523-BCC2-D3480E3A6A31](https://user-images.githubusercontent.com/64974946/164643370-88fcc20c-41ef-4af5-9f21-ddc9d0ccec58.png)

pleased to have completed octordle in 3, though.

**Comment by kmc059000** [comment]
Its a joke. Octo=eight. The daily one today is #88. Ha ha. Some people get it, some dont.
