### ISSUE TITLE
Letter that appears only once in word is colored as though it appears twice

### ISSUE THREAD

**Issue by brentcwilson** [kmc059000/octordle#16]
Consider the following gameplay:

![image](https://user-images.githubusercontent.com/1761003/169702123-c51b6c40-e93e-4d32-9b6e-b1ba1e347e01.png)

Notice that on the fifth guess (CONDO), the first letter O is colored green and the second is colored yellow. This suggests that the correct word is in the form CONO_, which is false. The second O should not be colored.

I have played many games of Octordle and this is the first time I've noticed this bug. I don't know if that means I'm unobservant; if this is a recent regression; or if I stumbled across some sort of edge case.

**Comment by DanFu09** [comment]
![F43CD0E4-6934-4DCB-B37C-BB2310C65A24](https://user-images.githubusercontent.com/4600866/169706459-5a21d3ec-ef53-40ae-a6dc-6d21e24b7675.jpeg)
 Another example

**Comment by kmc059000** [comment]
This should be fixed in the new version now. let me know if that is not the case.
