### ISSUE TITLE
Solutions coinciding with Quordle?

### ISSUE THREAD

**Issue by arancaytar** [kmc059000/octordle#18]
I generally do both every day, and haven't noticed like this happening before. Today I see that the first four solutions for Octordle 131 are exactly identical to the four solutions of Quordle 131, in the same order. <details>
  <summary>Spoiler warning</summary>
  
SCOPE BLOKE ROACH BONGO <- same for quordle and octordle
QUERY BORAX UPPER CLOTH
  
</details>

I don't know if this was a fluke or a change to the RNG (or solution pool) that is going to cause this every time now, but it'd be a pity to have the two puzzles mutually spoil each other by having the same solutions.

(Reporting this on the more active and more recently changed repo, in case it was something recent that caused this to happen.)

**Comment by kmc059000** [comment]
Theyre based on the same original code, though octordles RNG was tweaked from the beginning. Perhaps it is a fluke, perhaps quordle accidentally changed theirs to match octordles. Ill check again tomorrow to see if theyre the same and will fix if it matches again.

**Comment by kmc059000** [comment]
@arancaytar well the twitter reaction to this was pretty horrible. I've changed the RNG logic so there is a new version of 131 now if you refresh your browser. And I tweaked it slightly so it hopefully doesn't happen again.
