### ISSUE TITLE
K not marked as used when played near the end of a game?

### ISSUE THREAD

**Issue by bkovitz** [kmc059000/octordle#5]
I love Octordle!! Many thanks for posting it.

I think I found a bug. Today (Octordle #48) is the second time I've typed a K and had it not get marked as used in the keyboard at the bottom of the window. (I should have typed a T but that was my own error.) This is in Google Chrome 98.0.4758.109 (arm64).

<img width="422" alt="Screen Shot 2022-03-13 at 10 11 47 PM" src="https://user-images.githubusercontent.com/4142015/158092991-982bdae6-0e12-4b66-872c-d7d621d326cd.png">
g

**Comment by kmc059000** [comment]
This was fixed the other day. Please let me know if it is still not working.
