### ISSUE TITLE
Feature Request: Only share the number/clock emojis.

### ISSUE THREAD

**Issue by charlieholder** [kmc059000/octordle#9]
Can we have a version of the results on mobile that is just the:
> Daily Octordle #57
> 5️⃣9️⃣
> 4️⃣7️⃣
> 6️⃣🔟
> 🕚8️⃣

All of the posts I see on social media (Facebook, Twitter, etc) are generally about the number of guesses used to solve all 8 words. The character length for Twitter won't support the entire results being pasted because the boxes add too much markup. iMessage isn't wide enough to display the results properly. In Whatsapp the message is so long you can't really see the entire thing without scrolling.

No one I talk about Octordle with is really interested in the black, green, and yellow squares for how each of the 8 words played out. We talk about how many rounds it took to get the words. If we play Wordle we do, but only because it's short and sweet.

I don't play on desktop so I'm not able to selectively copy the results. I can share the results and start conversations with people better on mobile because I have access to more apps.

Not trying to be critical at all. Please don't interpret this as such. Love the game. Addicted to it. Hoping to have a better experience sharing it with people and talking about it.

Thanks!

**Comment by kmc059000** [comment]
I just deployed this. I had been meaning to do this, so this just forced my hand.

I don't use the sharing feature much, so if you have any problems, please let me know and I can fix!

Thanks!

**Comment by jackgreenburg** [comment]
Is there a way to still send all the squares? I fully understand the desire to not have them, but it was a feature I personally liked (I always enjoyed seeing how a few of these bad boys ⬜️🟩🟩🟩🟩 completely ruin a good attempt). Of course, no worries if there is no way to send them, as I’ll continue to enjoy the game regardless.
